### ISSUE TITLE
Problem parsing go.mod since k6 v0.32.0 update

### ISSUE THREAD

**Issue by david-gourde** [k6io/xk6#19]
Since the k6 update `v0.32.0` went live (earlier today), the extension I was working on stopped working. The error I get is:

```
go: github.com/k6io/k6@v0.32.0: parsing go.mod:
	module declares its path as: go.k6.io/k6
	        but was required as: github.com/k6io/k6
```

I started having this error even without updating anything, and trying to build with `v0.31.1` or `v0.32.0`. k6 [mentions a breaking change for the xk6 extensions](https://github.com/k6io/k6/pull/2010), but I do not know how to fix this.

The expected outcome is that the `xk6 build` command works, either with `v0.31.1` or `v0.32.0`.

**Comment by na--** [comment]
Replace the `github.com/k6io/k6` imports in your extension with `go.k6.io/k6`, then delete `github.com/k6io/k6` from your `go.mod` and `go.sum` files and run `go get go.k6.io/k6@master && go mod tidy` in your repo.

**Comment by na--** [comment]
I just realized we'd forgotten to release a new xk6 version after the k6 v0.32.0 release :man_facepalming: That might not have been a problem if you installed the latest xk6 from source, but if you used the official releases, it could have tripped you up as well :disappointed: Just tagged and released this: https://github.com/k6io/xk6/releases/tag/v0.4.1

**Comment by MStoykov** [comment]
I have gone through most extensions in [this list](https://k6.io/docs/ecosystem/) and have made PRs or commits in my repository doing the required change. As an example this [commit](https://github.com/MStoykov/xk6-counter/commit/0d2fd2f2f5d79a76934e0c6343ac67fb1a8ce091) from one of my simple extensions. 

I did not do this by hand what I did was basically ran 
```shell
rg  github.com/loadimpact/k6 -l -0  | xargs -0 sed -i 's|github.com/loadimpact/k6|go.k6.io/k6|g'
go mod edit -require go.k6.io/k6@v0.32.0 
go mod tidy
```
And then edit the READMEs if required

**Comment by david-gourde** [comment]
Thanks @na-- for releasing a new xk6 version!
